import type { Metadata } from "next";
import "./globals.css";
import { Albert_Sans, Montserrat_Alternates } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import heroImage from "@/public/aboutscreen_image.png";
import printForgeLogoIcon from "@/public/printforge-logo-icon.svg"
import printForgeLogo from "@/public/printforge-logo.svg"

const albertSans = Albert_Sans({
  subsets: ["latin"],
  display: "swap",
});

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat-alternates",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.className} ${montserratAlternates.variable} antialiased`}
      >
        <header className="w-full bg-white">
          <nav className="flex justify-between px-6 py-4">
            <div className="relative cursor-pointer">
              {/* Desktop logo */}
               {/* Since we are using the Image Component from nextjs instead of html <img> 
               the height & width we provide here are the original dimensions of the image*/}
              <Image
                src={printForgeLogo}
                alt="PrintForge Community - A group of makers collaborating on 3D printing projects"
                width={100}
                height={100}
                className="w-[200px] h-auto hidden md:block"
              />
              {/* Mobile logo */}
              <Image
                src={printForgeLogoIcon}
                alt="PrintForge Community - A group of makers collaborating on 3D printing projects"
                width={100}
                height={100}
                className="w-[40px] h-auto block md:hidden"
              />
            </div>
            <ul className="flex items-center gap-2.5">
               <li className="text-sm uppercase cursor-pointer">
                <Link href="/3d-models">3D Models</Link>
              </li>
              <li className="text-sm uppercase cursor-pointer">
                <Link href="/about">About</Link>
              </li>
            </ul>
          </nav>
        </header>
        {/* In the childern the page.tsx gets rendered*/ }
        {children}
        <footer>
          <ul>
            <li>Email</li>
            <li>Social Media</li>
            <li>Trademark</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
